### ISSUE TITLE
Can't upload docx files with the upload form.

### ISSUE THREAD

**Issue by kuzmamar** [bezirovoviku/document-generator#10]
The form does not reckognize docx files.

**Comment by tomasbedrich** [comment]
What do you mean by "recognising docx"? Are you sure, you have a latest code and migrated database? I have tested uploading using API and dashboard and both works fine.
Can you please attach a log report (stored in `storage/log/laravel.log`)?

**Comment by kuzmamar** [comment]
I used your server http://docgen.tbedrich.cz/ so look there if something was logged.
I used libreoffice writer to generate that docx file. Maybe there is some problem with mime types.
I send it to @SkaceKamen and he said that it does not work for him either.

**Comment by tomasbedrich** [comment]
Can you please attach the document here?

**Comment by kuzmamar** [comment]
Here is the file
[example_template.docx](https://github.com/bezirovoviku/document-generator/files/26124/example_template.docx)

**Comment by tomasbedrich** [comment]
You are right, it has got a mime-type of `application/zip`. :sweat:
I can remove the mime-type check, but I don't know, how @SkaceKamen's generators will handle possible bad inputs. :grey_question:

**Comment by tomasbedrich** [comment]
Solved by #11. Please try it again and consider closing this issue.

**Comment by SkaceKamen** [comment]
Tried and upload works now.
