### ISSUE TITLE
Allow uploading json data for templates using dashboard

### ISSUE THREAD

**Issue by SkaceKamen** [bezirovoviku/document-generator#12]
Altrought main point of this application is the API used to generate documents, maybe it would be useful to be able to create request using dashboard.

The data provided would be in either JSON or CSV format and user would be able to select other params throught web interace.
CSV would work simply, it would require first line to be header, which would indicate variable names, each line would then be new document with variables under each column. CSV is widely used amongst bussines users.
Note: When uploading data, there will have to be file encoding selection as CSV is usually saved in regional encoding.

It would also be needed to display complete requests with links to download on dashboard.

**Comment by SkaceKamen** [comment]
This should take aroud 4 hours

**Comment by tomasbedrich** [comment]
> It would also be needed to display complete requests with links to download on dashboard.

This should be solved by #14

**Comment by tomasbedrich** [comment]
Should be solved by 2a5daa7, please check. User can now create a request from template detail page and when #14 will be done, the request result can also be downloaded and viewed on its separate page.

**Comment by SkaceKamen** [comment]
Would it be possible to convert it to web form instead of entering raw JSON data? Apart from testing, point of this feature was to allow BFU create request

**Comment by tomasbedrich** [comment]
No problem, I can create a form. But where to get a field list?

**Comment by SkaceKamen** [comment]
Well, for now it would be just select of template, optional callback_url, and input data type, CSV / JSON, and file input.
File contents would then be inserted to data parameter of request, including its type.
Data type will be new parameter in Create request method, which will allow requester to pass CSV/JSON/XML into data parameter. This will be part of the #19 I'm currently working on.

**Comment by tomasbedrich** [comment]
Well, it is possible, but I think this won't help BFU users to create a request – they still would have to create a file in JSON / CSV format and select it.

I think we can create a separate issue to add these fields:

- callback_url
- input_type

At least because the estimated time complexity of 4 hours was guessed just to create this version of template detail page.

**Comment by SkaceKamen** [comment]
Well, BFU usually have the CSV file ready to go. It is still much easier to enter just the data, not entire request, where you woul need to combine JSON and CSV.

Estimated complexity was including this form.

**Comment by tomasbedrich** [comment]
Okay, what about adding the fileds, while keeping the current textarea still in place? I think it is useful for testing.

BTW the textarea accepts only the `data` field from request – its easier than you think. :wink:

**Comment by SkaceKamen** [comment]
OK, moving additional improvements to new task
