### ISSUE TITLE
Add TOC to documentation

### ISSUE THREAD

**Issue by tomasbedrich** [bezirovoviku/document-generator#16]
Almost every documentation I know has TOC. I think we should also include one into our page.

Examples:
- https://dev.twitter.com/overview/documentation
- https://developers.facebook.com/docs
- http://docs.docgen.apiary.io/

**Comment by SkaceKamen** [comment]
This is duplicate of #13

**Comment by tomasbedrich** [comment]
I don't see any mention about TOC in that issue.
