### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by tomasbedrich** [bezirovoviku/document-generator#8]
Rewrite using [Laravel built-in testing methods](http://laravel.com/docs/5.1/testing#testing-json-apis) if possible.

- better coverage would be also great
- update readme - add guide to run tests

**Comment by tomasbedrich** [comment]
+ better coverage would be also great

**Comment by tomasbedrich** [comment]
- update readme - add guide to run tests

**Comment by SkaceKamen** [comment]
This will probably take about 5 hours, depending on tested functionality.
